config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  resources :warehouses, only: [:show, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/warehouse.rb
class Warehouse
  attr_accessor :id, :name, :code, :address, :description, :postal_code, :city, :state, :postal_code, :total_area, :useful_area
  def initialize(id:, name:, code:, address:, description:, city:, state:, postal_code:, total_area:, useful_area:)
    @id = id
    @name = name
    @code = code
    @address = address
    @description = description
    @city = city
    @state = state
    @postal_code = postal_code
    @total_area = total_area
    @useful_area = useful_area
  end

  def self.all
    response = Faraday.get("http://127.0.0.1:3000/api/v1/warehouses")
    result = []
    if response.status == 200
      warehouses = JSON.parse(response.body)
      warehouses.each do |w|
        result << Warehouse.new(id: w["id"], name: w["name"], code: w["code"], address: w["address"], description: w["description"], 
          city: w["city"], state: w["state"], postal_code: w["postal_code"], total_area: w["total_area"], useful_area: w["useful_area"])
      end
    else
      return nil
    end
    return result
  end

  def save(w)
    response = Faraday.post('http://127.0.0.1:3000/api/v1/warehouses') do |req|
      req.headers['Content-Type'] = 'application/json'
      req.body = {"name": w.name,
        "code": w.code,
        "description": w.description,
        "address": w.address,
        "city": w.city,
        "state": w.state,
        "postal_code": w.postal_code,
        "total_area": w.total_area,
        "useful_area": w.useful_area,
        "category_ids": 1}.to_json
      end

    if response.status == 201
      return true
    end
    return false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @warehouses = Warehouse.all

    if @warehouses.nil?
      flash.now['alert'] = 'Não foi possível acessar o banco de dados dos galpões'
    end
  end
end

app/controllers/warehouses_controller.rb
class WarehousesController < ApplicationController
  def show
    response = Faraday.get("http://127.0.0.1:3000/api/v1/warehouses/#{params[:id]}")
    @warehouse = []
    if response.status == 200
      @warehouse = JSON.parse(response.body)
    else
      flash.now[:alert] = 'Não foi possível carregar dados dos galpões'
    end
  end

  def new
  end

  def create
    @warehouse = Warehouse.new(id: params[:id], name: params[:name], code: params[:code], address: params[:address], description: params[:description],
                  city: params[:city], state: params[:state], postal_code: params[:postal_code], total_area: params[:total_area], useful_area: params[:useful_area])
  
    if @warehouse.save(@warehouse)
        redirect_to root_path, notice: 'Galpão registrado com sucesso'
    else
      flash[:alert] = 'Não foi possível gravar o galpão'
      render 'new'
    end        
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1>Galpões</h1>
<%= flash['alert'] %>

<% unless @warehouses.nil? %>
  <% if @warehouses.empty? %>
    <div class="info">Nenhum galpão disponível</div>
  <% end %>

  <% @warehouses.each do |w| %>
    <%= link_to w.name, warehouse_path(w.id)  %>
    <%= w.code %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WarehouseConsumer</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav>
        <%= link_to 'Cadastrar Galpão', new_warehouse_path %>
      </nav>
    </header>
    <%= flash[:notice] %>
    <%= yield %>
  </body>
</html>

app/views/warehouses/new.html.erb
<%= form_with url: warehouses_path do |form| %>
  <div class="form-group">
    <%= form.label :name, 'Nome' %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :code, 'Código' %>
    <%= form.text_field :code, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :description, 'Descrição' %>
    <%= form.text_area :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :address, 'Endereço' %>
    <%= form.text_field :address, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :city, 'Cidade' %>
    <%= form.text_field :city, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :state, 'Estado' %>
    <%= form.text_field :state, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :postal_code, 'CEP' %>
    <%= form.text_field :postal_code, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :total_area, 'Área Total' %>
    <%= form.text_field :total_area, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :useful_area, 'Área Útil' %>
    <%= form.text_field :useful_area, class: "form-control" %>
  </div>

  <%= form.submit 'Gravar', class: 'btn btn-primary' %>
<% end %>

app/views/warehouses/show.html.erb
<% if @warehouse.empty? %>
  <%= flash[:alert] %>
<% else %>
    <h1><%= @warehouse["name"] %></h1>
    <h2><%= @warehouse["code"] %></h2>

    <dl>
      <dt>Descrição</dt>
      <dd><%= @warehouse["description"] %></dd>

      <dt>Endereço</dt>
      <dd><%= @warehouse["address"] %> - <%=  @warehouse["city"] %>/<%=  @warehouse["state"] %></dd>

      <dt>CEP:</dt>
      <dd><%= @warehouse["postal_code"] %></dd>

      <dt>Área Total:</dt>
      <dd><%= @warehouse["total_area"] %> m2</dd>

      <dt>Área Útil:</dt>
      <dd><%= @warehouse["useful_area"] %> m2</dd>
    </dl>
<% end %>